package ejbtestproject.ejb;

import javax.ejb.Stateless;

/**
 * Created with IntelliJ IDEA.
 * User: Simple
 * Date: 09.04.14
 * Time: 22:17
 * To change this template use File | Settings | File Templates.
 */
@Stateless
public class TestBean
{
    public String getMessage() {
        return "This message was generated by simple ejb";
    }
}
